### ISSUE TITLE
Issues : to do list for sapsuckRz

### ISSUE THREAD

**Issue by oseibon2** [ReproducibleQM/sapsuckRz#1]
### Introduction
3/30/2017
Courtney working on currently

### Methods
4/6/2017
Isaac sent email to Doris (response expected by 4/13/17) 

### Results
4/11/2017

### Conclusions/Discussion
4/13/2017

### Abstract
4/20/2017

### Final written product for submission
4/27/2017

### Crop data
4/6/2017
Braeden working on currently

### Environmental data
4/4/2017
Chad working on currently

### Finalized figures
4/20/2017

## ** Presentations**
**EEBB** 
4/25/2017
Isaac submitted abstract, working on poster

**ESA** (if accepted)
TBD

**Comment by oseibon2** [comment]
Breakdown of tasks to be accomplished with roles assigned

**Comment by vandeynze** [comment]
I have scripts ready to attach crop data to observations. Initial vegan package adonis commands on corn and beans both return p<0.01, but I'm not sure how to interpret that.

**Comment by cbahlai** [comment]
Close and revise with new directions
